[contacts]
name = "Игорь Давидюк"
email = "igor.davidyuk@outlook.com"
address = "Хайфа, Израиль"
phone = "+972-53-572-5322"
github = "igor-davidyuk"
linkedin = "idavidyuk"

[summary]
target_position = "Специалист по данным, Инженер глубокого обучения"
about = ""

[summary.profile]
Summary = "Более 5 лет практического опыта в Python и глубоком обучении \nБолее 12 лет опыта исследований в академической и промышленной сферах"
Programming = "Python, Rust"
Technology = "Pytorch, Компьютерное зрение, Модели больших языков, HuggingFace, OpenCV, Numpy, gRPC"
# "Languages" = "Английский, Русский"

[[experience]]
position = "Инженер AI-фреймворков"
location = "Хайфа, Израиль"
company.name = "Intel"
company.website = "intel.com"
start_date = "Сентябрь 2020"
end_date = "Настоящее время"
details = [
  "Разработка платформы Intel Geti, позволяющей экспертам в различных областях решать задачи компьютерного зрения и обработки естественного языка",
  "Расширение охвата моделей библиотеки OpenVINO за счет интеграции ряда передовых глубоких нейронных сетей, охватывающих различные области, включая диффузию, обработку текста и аудио",
  "Исследование новых методов агрегации глубоких сверточных сетей и разработка открытого фреймворка OpenFL для федеративного обучения",
]
tags = ["Федеративное обучение", "ИИ"]

[[experience]]
position = "Специалист по данным"
location = "Нижний Новгород, Россия"
company.name = "Intelligichain"
company.website = "intelligichain.com"
start_date = "Октябрь 2019"
end_date = "Сентябрь 2020"
details = [
  "Разработка и реализация комплексных рабочих процессов адаптации нейронных сетей, включающих сбор данных, адаптацию модели и развертывание, для обеспечения надежной и эффективной производительности модели",
  "Проектирование и реализация компонентов когнитивной системы наблюдения, основанной на глубоком обучении",
  "Разработка приложений ИИ, встроенных в умные камеры",
]
tags = ["Глубокое обучение", "Разработка"]

[[experience]]
position = "Исследовательский ассистент"
location = "Новосибирск, Россия"
company.name = "Институт ядерной физики имени Г. И. Будкера"
company.website = "https://www.inp.nsk.su/budker-institute-of-nuclear-physics"
start_date = "Сентябрь 2015"
end_date = "Сентябрь 2019"
details = [
  "Теория агрегации для глубоких сверточных сетей и разработка открытого фреймворка OpenFL для федеративного обучения",
  "Работа по модернизации и поддержке инфраструктуры Новосибирского свободно-электронного лазера",
  "Представление результатов исследований на многочисленных международных конференциях по физике в виде устных и постерных докладов",
  "Авторство нескольких исследовательских статей, опубликованных в рецензируемых журналах",
]
tags = ["Физика", "Исследования"]

[[education]]
degree = "Магистр наук"
university.name = "Новосибирский государственный университет"
university.website = "http://www.nsu.ru"
location = "Новосибирск, Россия"
major = "Физика ускорителей"
start_date = "2013"
end_date = "2015"
# start_date = "Сентябрь 2013"
# end_date = "Июнь 2015"
gpa = "4.74"
dissertation = "Разработка переменнопериодного ундулятора для второй стадии Новосибирского свободно-электронного лазера"

[[education]]
degree = "Бакалавр наук"
university.name = "Новосибирский государственный университет"
university.website = "http://www.nsu.ru"
location = "Новосибирск, Россия"
major = "Физика"
start_date = "2009"
end_date = "2013"
# start_date = "Сентябрь 2009"
# end_date = "Июнь 2013"
gpa = "4.2"
dissertation = ""