[document]
use_emoji = false
add_location_footnote = true

[page]
# paper_format = "a4"
paper_format = "us-letter"

[font]
add = "Helvetica Nueu"
name = "Arial"
# name = "Linux Biolinum"

[font.size] 
name = "25pt"
heading_large = "20pt"
heading = "14pt"
description = "11pt"
tags = "8pt"
education_description = "8pt"
contacts = "11pt"
