[document]
use_emoji = false

[page]
# paper_format = "a4"
paper_format = "us-letter"

[font]
add = "Helvetica Nueu"
name = "Linux Biolinum"
[font.size] 
name = "34pt"
heading_large = "17pt"
heading = "14pt"
description = "10.5pt"
tags = "8pt"
education_description = "8pt"
contacts = "8pt"
