[page]
# paper_format = "a4"
paper_format = "us-letter"

[font]
add = "Helvetica Nueu"
name = "Linux Biolinum"
[font.size] 
name = "33pt"
heading_large = "16pt"
heading = "13pt"
description = "10pt"
tags = "8pt"
education_description = "8pt"
contacts = "8pt"
