name: Render PDF
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.pdf'
jobs:
  render-paper:
    env:
      TARGET_FILE_NAME=davidyuk_cv.pdf
    runs-on: ubuntu-latest
    permissions:  
      contents: write  # 'write' access to repository contents
    steps:
      - uses: actions/checkout@v4

      ## Install fonts
      # - uses: fontist/setup-fontist@v2
      # - run: fontist install "Helvetica Nueu"

      - uses: typst-community/setup-typst@v3
      - run: typst compile main.typ $TARGET_FILE_NAME # --font-path ~/.fontist/fonts

      ## Make a release with the PDF file
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: $TARGET_FILE_NAME

      ## Push the PDF file
      # - run: |
      #     git config --local user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git commit -a -m "update cv"
      # - uses: ad-m/github-push-action@master
